# Generated by Django 5.1.6 on 2026-04-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
